version: '2'

services:
  backend:
    build:
        context: ./backend
        dockerfile: Dockerfile
    image: weatherapp_backend
    ports: 
      - 9000:9000
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: weatherapp_frontend
    ports: 
      - 8000:8000