version: '3'

services:
  frontend:
    build:
      context: ./frontend
      args:
        - NODE_ENV=development
    command: npm start
    ports: 
      - 8000:8000
    volumes:
      - ./frontend:/opt/app
      - nonodefront:/opt/app/node_modules
    environment:
      - NODE_ENV=development
  backend:
    build:
      context: ./backend
      args:
        - NODE_ENV=development
    command: npm run dev 
    ports: 
      - 9000:9000
    volumes:
      - ./backend:/opt/app
      - nonodeback:/opt/app/node_modules
volumes:
  nonodefront:
  nonodeback: